//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;


public class CoinAnimator : MonoBehaviour {
	
	public Transform center;
	public Transform ring;
	public int y = 0;
	public bool upDown = false;
	// Update is called once per frame.
	void Update ()
	{
		center.localRotation*=Quaternion.Euler(0f,Time.deltaTime*-120f,0f);
		ring.localRotation*=Quaternion.Euler(0f,Time.deltaTime*120f,0f);
		if(upDown == false){
			ring.localPosition += Vector3.up * 0.1F;
			center.localPosition += Vector3.up * 0.1F;
		}
		else{
			center.localPosition += Vector3.down * 0.1F;
			ring.localPosition += Vector3.down * 0.1F;
		}
		if(y == 15){
			if(upDown == false){
				upDown = true;
				y=0;
			}	
			else{
				upDown = false;	
				y=0;
			}
		}
		
		y++;
		
	}
	
}

