//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;


public class GameSounds : MonoBehaviour {

	public AudioSource coin_Noise ;



	public void playCoinAudio(){
		coin_Noise = gameObject.AddComponent("coin_earn") as AudioSource;
		coin_Noise.Play();


	}


}